version: '3.4'

services:
  postgres:
    container_name: postgres_database
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: graphql
      POSTGRES_PASSWORD: graphql

volumes:
  postgres-data: